net:
  proxy:
    # 代理相关信息
    - ip: 127.0.0.1
      port: 1080
      type: SOCKS

ai:
  maxNum:
    basic: 5
    wechat: 100
    star: 100 #
    starTry: 30
    invited: 0.1 # 被邀请
    inviteNum: 0.2
    starNumber: 4000 # 目前为 4000
  source: # 支持的AI模型
    - CHAT_GPT_3_5
    - CHAT_GPT_4
    - PAI_AI
    - XUN_FEI_AI

# chatgpt
chatgpt:
  main: CHAT_GPT_3_5
  conf:
    CHAT_GPT_3_5:
      keys:
        -
      proxy: true # 表示走上面的代理进行访问
      apiHost: https://api.openai.com/
      timeOut: 900
      maxToken: 3000
    CHAT_GPT_4:
      keys:
        -
      proxy: true
      apiHost: https://api.openai.com/
      timeOut: 900
      maxToken: 200000
  number:
    # 普通用户
    normal: 50
    vip: 100

# 阿里通义千问
ali:
  apiKey: sk-cd1b6c8c18d64c52b88c51114346fbb0
  model: qwen-plus

# 讯飞星火
xunfei:
  hostUrl: http://spark-api.xf-yun.com/v3.5/chat
  domain: "generalv3"
  appId: 8ed64cca
  apiKey: 1cb78fcabb96b0ef42ae30e8610e67af
  apiSecret: NTQ1NDk0MWE1Y2M4ZjllYTY5MDRjOGY3

# 智谱AI
zhipu:
  requestIdTemplate: "request-id-%s"
  apiSecretKey: 8da41764e5217902602d534c6ebb300a.IJP7jopkUehKUvEm
  model: glm-4